"use client"
import { useToggleState } from "@/store/toggleStore"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { useEffect } from "react"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { isChecked } = useToggleState()
  useEffect(() => {
    let isMount = true
    if (isChecked && isMount) {
      document.documentElement.setAttribute(
        "data-mode",
        isChecked ? "dark" : "light"
      )
      document.documentElement.className = isChecked ? "dark" : "light"
    }
    return () => {
      isMount = false
      document.documentElement.removeAttribute("data-mode")
    }
  }, [isChecked])
  return (
    <html lang="en" data-mode="light">
      <body className={`${inter.className} h-full dark:bg-black`}>
        {children}
      </body>
    </html>
  )
}
